name       : libaacs
version    : 0.8.0
release    : 2
source     :
    - http://download.videolan.org/pub/videolan/libaacs/0.8.0/libaacs-0.8.0.tar.bz2 : 5e44545c7c4cb48bea49ff6b19d148416663593d6125ac8734776df21154ba94
license    : LGPL-2.1
summary    : libaacs is a research project to implement the Advanced Access Content System specification.
description: |
    libaacs is a research project to implement the Advanced Access Content System specification.
builddeps  :
    - libgcrypt-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
