name       : libaacs
version    : 0.9.0
release    : 5
source     :
    - http://download.videolan.org/pub/videolan/libaacs/0.9.0/libaacs-0.9.0.tar.bz2 : 47e0bdc9c9f0f6146ed7b4cc78ed1527a04a537012cf540cf5211e06a248bace
license    : LGPL-2.1
summary    : libaacs is a research project to implement the Advanced Access Content
    System specification.
component  : multimedia.codecs
description: |
    libaacs is a research project to implement the Advanced Access Content System specification.
builddeps  :
    - libgcrypt-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
