name       : libaacs
version    : 0.8.1
release    : 3
source     :
    - http://download.videolan.org/pub/videolan/libaacs/0.8.1/libaacs-0.8.1.tar.bz2 : 95c344a02c47c9753c50a5386fdfb8313f9e4e95949a5c523a452f0bcb01bbe8
license    : LGPL-2.1
summary    : libaacs is a research project to implement the Advanced Access Content System specification.
component  : multimedia.codecs
description: |
    libaacs is a research project to implement the Advanced Access Content System specification.
builddeps  :
    - libgcrypt-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
